# docker run --name=todo-db -e POSTGRES_PASSWORD='123qwe' -p 5432:5432 -d --rm postgres
# psql -h localhost -p 5432

# bind_addr = ":8080"
# log_level = "debug"
# database_url = "host=localhost user=admin password=admin dbname=postgres_db sslmode=disable"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123qwe"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env