docker run --name=todo-db -e POSTGRES_PASSWORD='123qwe' -p 5432:5432 -d --rm postgres

bind_addr = ":8080"
log_level = "debug"
database_url = "host=localhost user=admin password=admin dbname=postgres_db sslmode=disable"