port: "8080"

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

db_url: "host=localhost port=5432 user=postgres dbname=postgres password=123qwe sslmode=disable"